services:
  app:
    build:
      context: .
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: "3000"
      PROXY_HOST: 0.0.0.0
      PROXY_PORT: "8080"
      DATA_DIR: /app/.data
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - app-data:/app/.data

volumes:
  app-data:
